import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Trending from "../components/Trending";
import Popular from "../components/Popular";
import styles from "../styles/Home.module.css";
import News from "../components/News";
import Posts from "../components/Posts";

export default function Home() {
  return (
    <div className="bg-[#dae0e6]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ">
        {/* Navbar */}
        <Navbar />
        {/* Trending Today */}
        <Trending />
        <div className=" ">
          <div className="md:flex md:w-[85vw]   xl:w-[75vw]   md:mx-auto">
            <div className=" md:mx-auto ">
              {/* Popular Posts */}
              <Popular />
              <Posts />
            </div>

            {/* News */}
            <News />
          </div>
        </div>

        <div className="h-screen"></div>
      </div>
    </div>
  );
}
